//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Ubicación { get; set; }
        public string Operario { get; set; }
        public string Cargadora { get; set; }
        public string Producto { get; set; }
        public string Función { get; set; }
        public string Secuencia { get; set; }
        public string Peso { get; set; }
        public string Actividad { get; set; }
        public string Origen { get; set; }
        public string Camión { get; set; }
        public string Dirección { get; set; }
        public string Datos5 { get; set; }
        public string Tara { get; set; }
        public string Notas { get; set; }
        public string Ciclo { get; set; }
        public string Rendimiento { get; set; }
        public string Mascara { get; set; }
        public string FechaMina { get; set; }
        public string Turno { get; set; }
        public string SecuenciaID { get; set; }
        public long ID { get; set; }
    }
}
